### ISSUE TITLE
Ng include can't find the template file

### ISSUE THREAD

**Issue by THPubs** [pitr/angular-rails-templates#101]
Hi, Im trying to load the template using ng-include and it's not working. Here's my application.js :

    //= require jquery
    //= require jquery_ujs
    //= require angular
    //= require angular-rails-templates
    //= require lodash
    //= require_tree ../templates
    //= require_tree .

The template file is located in `assets/templates/person.html`
The index.html.erb file which have ng-include (Only the part that have it) :

    <li ng-repeat="item in dirList.list | filter:search">
        <ng-include src="'person.html'"></ng-include>
    </li>

The js file (only the first part) :

    angular.module('directoryApp', ['templates'])
        .controller('directoryController', function() {

            var dirList = this;

            dirList.toggle = true;

What might be the problem? The rest of the app is working!

**Comment by jademcgough** [comment]
this is probably related to #97
