### ISSUE TITLE
In Directive ng-include works but templateurl does not

### ISSUE THREAD

**Issue by jmillman** [pitr/angular-rails-templates#103]
Hi,
I created a directive and the templateurl does not work, but if I use a template with a div and an ng-include it does work.  It is the same directive and the same path.  It should work.

```
angular.module('app').directive('ottAddEditPosition', function(){
	return {
		restrict: 'A',
		replace: true,
		//templateUrl: 'assets/ottAddEditPosition.html'  //this does not work
		template: '<div data-ng-include src="\'assets/ottAddEditPosition.html\'"></div>'
	};
});
```

**Comment by pitr** [comment]
Closing as this is an old issue. Please message here if you want it reopened
