### ISSUE TITLE
Cache busted on every deploy (ART 0.5.0+)

### ISSUE THREAD

**Issue by jaybloke** [pitr/angular-rails-templates#104]
I noticed that on every deploy of my app the cache is busted on all of my assets even when there are no changes to the assets... all assets are re-fingerprinted. This wouldn't normally be a problem, but I have some 500+ assets and large js files to deal with. The only way to get the correct behaviour back was to downgrade to v0.1.4.

Rails 4.1.8, Ruby 2.2.2
Capistrano 3.4 for deployment.
sprockets-rails 2.3.1

config/initializers/art.rb

    config.angular_templates.ignore_prefix  = %w(shared/templates/ public/templates/ member/templates/ professional/templates/ templates/)

    config.angular_templates.htmlcompressor = {
      remove_intertag_spaces: false
    }

**Comment by jaybloke** [comment]
Correction: It appears only v0.2.0 is problematic on deploys.

**Comment by jaybloke** [comment]
This is what I think is happening: On any given deploy, capistrano changes to the current release folder when compiling assets e.g:

    cd /home/deploy/app/releases/20150701072428 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.2 RAILS_ENV=staging ~/.rbenv/bin/rbenv exec bundle exec rake assets:precompile )

And in ART we have:

    config.angular_templates.inside_paths   = [Rails.root.join('app', 'assets')]

With capistrano, Rails.root always changes on every deploy because the release version changes. And the md5 hash you append to config.assets.version thus changes too:

      app.config.assets.version = [
        app.config.assets.version,
        'ART',
        Digest::MD5.hexdigest("#{VERSION}-#{app.config.angular_templates}")
      ].join '-'

I'm not very familiar with the workings of sprockets, but could a simple

    File.join(File.dirname(__FILE__), 'app', 'assets')

do the trick? (he naively says).

**Comment by thekendalmiller** [comment]
Fixed by https://github.com/pitr/angular-rails-templates/pull/115
