### ISSUE TITLE
RegexpError: empty range in char class

### ISSUE THREAD

**Issue by tridnguyen** [pitr/angular-rails-templates#105]
If the folder path for inside_paths has a hyphen in the folder path, an error is thrown on line 15 of template.rb:

```
@asset_should_be_processed = configuration.inside_paths.any? { |folder| file.match(folder.to_s) }
```

I resolved this by escaping the hyphens with gsub:

```
@asset_should_be_processed = configuration.inside_paths.any? { |folder| file.match(folder.to_s.gsub('-', '\-')) }
```

Is there another way of getting around this or is this a viable solution for a pull request?

**Comment by pitr** [comment]
`config.inside_paths` needs to be a valid regex
