### ISSUE TITLE
Path parsing issues under Windows

### ISSUE THREAD

**Issue by stewartmatheson** [pitr/angular-rails-templates#106]
in template.rb it looks like angular-rails-templates removes the rails root path by doing a sub based on a regular expression. This causes issues on windows when any folder within this path starts in a digit. Consider the following autogenerated path from team city

`C:\TeamCity\buildAgent\work\2a9b7d1e3ef2f28e\`

Valid path however as soon as you parse it with the following

`locals[:source_file] = "#{scope.pathname}".sub(/^#{Rails.root}\//,'')`

you get

`RegexpError: (RegexpError) invalid backref number/name`

The issue springs from \2 in the regexp however this will happen for any path with a digit in windows. I suggest a patch that removes the regular expression parsing from the above line and replaces it with something more robust that will avoid this issue. If @pitr is happy I can provide a patch in the coming few days.

**Comment by pitr** [comment]
Happy if you could provide a patch. I don't use Windows and can't replicate this.

**Comment by pitr** [comment]
closing old task
