### ISSUE TITLE
templates outside of the folder `app/assets/javascripts/templates` dont load

### ISSUE THREAD

**Issue by ariera** [pitr/angular-rails-templates#107]
Hello guys!
First of all, thanks a lot to the maintainers of this project, it has save me already lots of time and you guys do a great job!

I have a question regarding the assets folder structure. This is how I would like mine to look like:

```
assets
   javascripts
      angular
          features
              featureX
                 templateX.html.slim
                 featureX.js.coffee
```
but `templateX.html.slim` doesnt get loaded
and in my application.js manifest i have

```
//= require_tree ./angular
```

The solution that I have found to get me going, in order to be able to load `templateX.html.slim`, is to use this alternative structure.

```
assets
   javascripts
      templates
         features
             featureX
                 templateX.html.slim
      angular
          features
              featureX
                 featureX.js.coffee
```

and make sure to require that `templates` tree in the manifest

```
//= require_tree ./templates
```

but that is a less desirable solution, as you can see there is a lot of folder structure repetition and would like to avoid it.

Is there a way to achieve this with `angular-rails-templates` ?

Thank you very much.

**Comment by kamnog** [comment]
+

**Comment by vnazarenko** [comment]
+

**Comment by diegotoral** [comment]
I'm trying to achieve the same without success! Would be awesome keep all feature related things in the same place.

**Comment by pitr** [comment]
closing old issue
