### ISSUE TITLE
Final template path when using inside_paths?

### ISSUE THREAD

**Issue by jmwohl** [pitr/angular-rails-templates#109]
Can't quite seem to get this right...

I have a use case where I want to pull template files from an external npm repo. From what I gather, I should be able to use `inside_paths` config option, something like so:

```ruby
config.angular_templates.inside_paths   = [Rails.root.join('app', 'assets'), Rails.root.join('node_modules', 'my-module', 'lib')]
```

Am I correct in thinking this should look for and load template files from within the `node_modules/my-module/lib` directory? If so, what is the final template path that will be available in the `$templateCache`?

Let's say there's a template at `node_modules/my-module/lib/common/header.html`. How would I access the template?

**Comment by pitr** [comment]
you cannot achieve this using `inside_paths`. Rails asset pipeline only looks at `app/assets`, `lib/assets` and `vendor/assets` folders. You either need to add that node_modules path to Rails asset config, or create a soft link like `app/assets/javascripts/my-module` that points at the npm repo.
