### ISSUE TITLE
v0.1.5 & 0.2.0 need older version of sprockets than sass-rails

### ISSUE THREAD

**Issue by akholodenko** [pitr/angular-rails-templates#110]
angular-rails-templates (~> 0.2.0) ruby depends on
      sprockets (~> 2) ruby

    sass-rails (~> 5.0.3) ruby depends on
      sprockets (3.0.3)

**Comment by bramski** [comment]
Is this going to be addressed?

**Comment by svisamsetty** [comment]
yes, I would like to know as well. if this is going to be addressed?

**Comment by werleo** [comment]
:+1:

**Comment by pitr** [comment]
Fixed by #126. Version 1.0.0.beta1 is out and supports Rails 4.2+ and Sprockets 3, I'll release version 1.0.0 once we are stable.
