### ISSUE TITLE
Other HTML that are outside "inside_paths" dont get to public folder

### ISSUE THREAD

**Issue by EduardoBraz** [pitr/angular-rails-templates#112]
Guys,

i am trying to use angular-rails-templates to compile some html files into my js but i also need to export other html files that wont be used by angular.

When i installed the gem the html files outside "inside_paths" stopped being exported.

My only configuration is:
```
config.angular_templates.inside_paths   = [Rails.root.join('app', 'assets', 'javascripts')]
```

Do you know if the gem allows other html to be exported (and not be compiled into js)?

**Comment by EduardoBraz** [comment]
Guys,

i explored the code and found out that, as the ".html" is bounded to the AngularRailsTemplates engine

```
app.assets.register_engine '.html', AngularRailsTemplates::Template
```

and that the mime-type is decided inside to be javascript, i cant render other html in other strategy. So i'm  trying other strategy than using the gem. If you see something different, please, i'd be glad to know.

**Comment by thekendalmiller** [comment]
We also his this problem recently. We have app/assets/html that we use to compile 404 and 500 pages.

What we decided to do what change this sprocket engine to register for '.htm' extension and our angular templates are now .htm.

This is the line that changed. https://github.com/pitr/angular-rails-templates/blob/master/lib/angular-rails-templates/engine.rb#L56

**Comment by EduardoBraz** [comment]
Nice, i will try this later. I have some angular templates that are ".html.erb" and i dont know if they will compile. I'll try and later give you a feedback.

**Comment by thekendalmiller** [comment]
Good luck! We also have angular templates as 'htm.erb' that include images and they are still working.

rails (4.0.13)
sprockets (2.12.3)
sprockets-rails (2.3.1)

**Comment by pitr** [comment]
closing old issue
