### ISSUE TITLE
sprockets versioning (installation instructions)

### ISSUE THREAD

**Issue by cleechtech** [pitr/angular-rails-templates#119]
I was stuck for a while because I was trying to use this gem with sprockets 2.11. I had to run `$ bundle update sprockets` and add `gem 'sprockets', '2.12.3'` to my Gemfile for a rails 4 app I recently created.

Please include a note in the Readme about sprockets versioning. I am happy to submit a PR. What is up with sprockets and this gem?

**Comment by droptheplot** [comment]
Got `NoMethodError: undefined method 'register_engine' for nil:NilClass` with `sprockets-rails` 3.0.0, forks fine with 2.3.2.

**Comment by pitr** [comment]
Fixed by #126. Version 1.0.0.beta1 is out and supports Rails 4.2+ and Sprockets 3, I'll release version 1.0.0 once we are stable.
