### ISSUE TITLE
add collaborators 

### ISSUE THREAD

**Issue by quinn** [pitr/angular-rails-templates#123]
this project is abandonware, @pitr allow others to merge pull requests.

**Comment by kieranklaassen** [comment]
+1

**Comment by quinn** [comment]
@pitr I'm using this in multiple live, production applications. Can I maintain this project please and thank you?

**Comment by pitr** [comment]
Good idea. Added @superchris will add more in the future.

**Comment by quinn** [comment]
Thank you!
