### ISSUE TITLE
Can't install latest beta.

### ISSUE THREAD

**Issue by alucardu** [pitr/angular-rails-templates#129]
In my gemfile I have `gem 'angular-rails-templates', '~> 1.0', '>= 1.0.0.beta2'` but when I run `bundle update` I get an error,

> Could not find gem 'angular-rails-templates (>= 1.0.0.beta2, ~> 1.0) ruby' in any of the gem sources
listed in your Gemfile or available on this machine.

**Comment by pitr** [comment]
Thanks for trying beta version! The reason you are having that problem is that 1.0.0.beta2 does not actually match `~> 1.0` since `1.0.0.beta2 < 1.0.0`. There hasn't been any issues with beta2 yet, so I'm planning to release 1.0 in a couple of days. Please let me know if you are having any problems.

**Comment by alucardu** [comment]
As you know angular-rails-template does not work with Sprockets 3+. But downgrading to Sprockets 2.12.4 is causing errors in my code. Am I correct in understanding that it's not yet possible to user angular-rails-template version 1.0?

**Comment by pitr** [comment]
1.0.0.beta2 is a version you want if you need Sprockets 3+ support

**Comment by alucardu** [comment]
Alright but what's the line I need to use to install it through the gemfile since `gem 'angular-rails-templates', '~> 1.0', '>= 1.0.0.beta2'` results in an error?

**Comment by pitr** [comment]
This should work:

```ruby
gem 'angular-rails-templates', '>= 1.0.0.beta2'
```

**Comment by alucardu** [comment]
Thank you very much for me helping me out. Works great now. Going to keep an eye on the whole beta > live situation.
