### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by normancapule** [pitr/angular-rails-templates#139]
Hello! Any help on this would be appreciated :)

I'm making a boilerplate using rails 5.0rc1 + angular 1.5. Some screenshots of what I see in the google chrome console:
<img width="1280" alt="screen shot 2016-06-17 at 11 59 40 am" src="https://cloud.githubusercontent.com/assets/780659/16140438/1298ccc0-3483-11e6-8ccd-b2c4a8fbe3c1.png">
<img width="926" alt="screen shot 2016-06-17 at 11 59 53 am" src="https://cloud.githubusercontent.com/assets/780659/16140441/1568dce2-3483-11e6-9b48-3df6925cacc7.png">

Also here is the repo of my boilerplate: https://github.com/normancapule/boilerplate1

**Comment by pitr** [comment]
```diff
```

**Comment by normancapule** [comment]
thank you so much!
