### ISSUE TITLE
Deprecation warning from sprockets 3.7.0

### ISSUE THREAD

**Issue by anhkind** [pitr/angular-rails-templates#143]
The current version `1.0.0` seems to give deprecation warning with `sprockets` `3.7.0`, can you help to fix that in the code? Thanks.

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (3 levels) in <class:Engine> at /Users/user/.rvm/gems/ruby-2.3.0/gems/angular-rails-templates-1.0.0/lib/angular-rails-templates/engine.rb:33)
```

**Comment by grosser** [comment]
@pitr did anyone work on a fix for this ?

**Comment by anhkind** [comment]
I found a fix for the same problem from `sass-rails` gem here https://github.com/rails/sass-rails/commit/0e85d0d282cdd99f54f91b84f44d059bb6225069, don't know if it helps...

**Comment by anhkind** [comment]
@pitr Do you have some time for this? I can also work on a PR for this myself, but if you can shed some light, it would be easier for me. Thanks.

**Comment by alfie-max** [comment]
Would there be a new release soon with this merge?

**Comment by bpinto** [comment]
Please? @pitr

**Comment by pitr** [comment]
v1.0.2 released with this fix

**Comment by grosser** [comment]
confirmed fixed, please close the issue :)
