### ISSUE TITLE
Rails functions in .erb templates for angular

### ISSUE THREAD

**Issue by mikeover** [pitr/angular-rails-templates#144]
I've got this configured and loading .html.erb templates successfully and it can run Ruby code with in, simple things such as interpolated strings.

However, I'm in a template where I want to create a form, and I get an undefined method error when I try to use either `simple_form_for` or just `form_for`.

Is there something extra that needs to be done to have access to these in the template?

**Comment by pitr** [comment]
Please see https://github.com/pitr/angular-rails-templates/issues/72#issuecomment-97140110
