### ISSUE TITLE
How to use Devise helper on template?

### ISSUE THREAD

**Issue by ohmygodvt95** [pitr/angular-rails-templates#153]
I want to use some functions in Devise Helper: current_user, user_signed_in? In the template. I tried but failed.
```ruby
Rails.application.config.after_initialize to
   Rails.application.assets.context_class.class_eval to
     Include ApplicationHelper
     Include ActionView :: Helpers
     Include Rails.application.routes.url_helpers
   End
End
```
I was able to use the path function, link_to ... but with devise is not done.
who can help me?. thank you.

**Comment by fourcolors** [comment]
👍 I could use this too.

**Comment by Looooong** [comment]
If you are using Sprocket 3, the interface is changed like this ([reference](https://stackoverflow.com/a/34732838)):

```ruby
Rails.application.config.assets.configure do |env|
  env.context_class.class_eval do
    # include SomeHelper
  end
end
```
