### ISSUE TITLE
Rails 5.1 compatibility?

### ISSUE THREAD

**Issue by chrismanderson** [pitr/angular-rails-templates#156]
Does this work with Rails 5.1, or should I look into Webpacker instead? Thanks!

**Comment by DavidMMelin** [comment]
+1

**Comment by redtachyons** [comment]
Yes, this gem is working fine with rails 5.1

**Comment by vicmaster** [comment]
@redtachyons You did not experienced problems with `Rails.application.routes.url_helpers` ?

**Comment by redtachyons** [comment]
No issues yet, our app is in production with rails 5.1

**Comment by vicmaster** [comment]
@redtachyons Interesting I have read about this, and other people have struggled with it. 🤔 let me take a look on it

**Comment by vicmaster** [comment]
Well, we were experiencing an issue related to this issue, https://github.com/pitr/angular-rails-templates/issues/45 I left a comment there about how we solved in case you have something similar than us. https://github.com/pitr/angular-rails-templates/issues/45#issuecomment-343248298

**Comment by mbuffa** [comment]
Did anyone encounter an issue with Rails 5.1.4 and Sprockets 3.7.1 with `failed to load template` errors?

**Comment by mbuffa** [comment]
Oh okay, apparently this is due to filenames collisions, which is mentioned on the readme. I suppose this is due to upgrading to a newer sprockets.

**Comment by DevilsNightsix** [comment]
I've just upgraded my app to rails 5.1 and stuck with error:
```
Sprockets::FileNotFound at /
couldn't find file './settings/layout.html' under '/app/app/assets/javascripts' with type 'application/javascript'
```
 i'm using:
* rails 5.1.0
* angular-rails-templates 1.0.2
* sprockets 3.7.1

angular-rails-templates are with default settings

any ideas?

**Comment by mathieujobin** [comment]
I have used this gem with Rails 5.2 and 6.1 with no problems
