### ISSUE TITLE
Support for Rails 7.1?

### ISSUE THREAD

**Issue by epugh** [pitr/angular-rails-templates#168]
Just updated to Rails 7.1 and discovered that this gem explicitly excludes 7.1..

**Comment by epugh** [comment]
Looks like this is the line preventing 7.1..  https://github.com/pitr/angular-rails-templates/blob/master/angular-rails-templates.gemspec#L19

**Comment by epugh** [comment]
I gave a quick stab at forking the repo and bumping it: https://github.com/pitr/angular-rails-templates/compare/master...epugh:angular-rails-templates:bump_rails_71?expand=1

I thought I could refer to it in my Gemfile, via 

```
gem 'angular-rails-templates', git: 'https://github.com/epugh/angular-rails-templates.git', branch: 'bump_rails_71'
```

but no luck so far..

**Comment by pughe2** [comment]
Okay, I figured out my challenge in getting it added to my Gemfile, and now it's working.

**Comment by mathieujobin** [comment]
Happy to see there is a couple of people still using this gem.

I'll be glad to make a release once you confirm everything is working.

if you open a PR, please stick with `<` and not `<=` 
also update the Github Action workflow file to include running tests on Rails 7.1.1
and make sure all test passes

thank you

**Comment by mathieujobin** [comment]
released as v1.2.1

**Comment by epugh** [comment]
Thank you!   It's going to be fun to figure out how to support my old AngularJS app and all the new HOTwire/Turbo stuff in Rails 7.1 at the same time.

**Comment by mathieujobin** [comment]
I do have an app with Angular 1.x and Hotwire. 
We also have pages using VueJS 2.x

We try not to load different JS framework on the same pages.

its not too bad.. 
obviously, we would want to deprecate everything old, but too much work for little value
