### ISSUE TITLE
Thoughts on supporting Rails 8?

### ISSUE THREAD

**Issue by epugh** [pitr/angular-rails-templates#171]
I know I have to make the migration from Sprockets to Propshaft.  Now sure what else will need doing.

**Comment by mathieujobin** [comment]
Thanks

**Comment by epugh** [comment]
No prob!  Will you cut a release?   I appreciate your helping us all who are stuck on Sprockets ;-).  

 My attempts to get to Propshaft have foundered on the fact that to get to Propshaft, I appear to have to add in css bundingly and js bundling, which has been too much...  ;-)

**Comment by nehresma** [comment]
Came here to ask about a rubygems.org release and saw @epugh already did.  Any chance of releasing out there @mathieujobin?

**Comment by nehresma** [comment]
Yeah, I have an old product that still requires support for a few more months before it is fully replaced.  :frowning_face:

**Comment by epugh** [comment]
I'm looking for some success stories of Angular1 app moved to propshaft etc....

**Comment by mathieujobin** [comment]
I can release it ... 

I'd like to hear about a success story about angular1 with propshaft... but nowawdays its easier to hire someone to rewrite it ... sad... though

**Comment by epugh** [comment]
> I can release it ...
> 
> I'd like to hear about a success story about angular1 with propshaft... but nowawdays its easier to hire someone to rewrite it ... sad... though

I hear you!  The project I steward, https://github.com/o19s/quepid we have slowly shrunk down what is in Angular1, but it's an open source project, and rewriting the core library would require someone to step up!   So I suspect Angular1 will be with that project for a long time to come...   

Thanks for keeping this gem up to date!
