### ISSUE TITLE
excluding namespace?

### ISSUE THREAD

**Issue by twmulloy** [pitr/angular-rails-templates#58]
I'm using `angular-rails-templates` `0.1.2` with a Spree app and for some reason the templates module is making its way into the Spree backed js manifest and throwing the following error. Removing the gem does indeed remedy the error. Removing `//= require angular-rails-templates` in the frontend js manifest still results in the same error.

    // Angular Rails Template
    // source: /Users/thomas/.rvm/gems/ruby-2.1.2@gemset/gems/spree_backend-2.2.2/app/assets/javascripts/spree/backend/index.html

    angular.module("templates").run(["$templateCache", function($templateCache) {
      $templateCache.put("spree/backend/index.html", '<!DOCTYPE html>\n<html>\n  <head>\n    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />\n    <style type="text/css">\n      html { height: 100% }\n      body { height: 100%; margin: 0; padding: 0 }\n      #map-canvas { height: 100% }\n    </style>\n    \n  </head>\n  <body>\n    <div id="map-canvas"/>\n  </body>\n</html>')
    }]);

The script that is injected in the `<head>` when the gem is included `<script src="/assets/spree/backend/index.js?body=1"></script>`, `Uncaught ReferenceError: angular is not defined` all default installation of the `angular-rails-templates` gem.

Here is the default Spree backend js manifest https://github.com/spree/spree/blob/2-2-stable/backend/app/assets/javascripts/spree/backend.js and I am not overriding this.

**Comment by ccashwell** [comment]
@jsanders that'd be great... I'm running into collisions galore when trying to use ART in conjunction with Web Components, which need not be processed. IMO the whole `register_engine` thing is totally overkill; rather than assuming someone might want `*.html` processed, it should be much more specific. I think your proposed `paths` setting would be fantastic.

**Comment by jsanders** [comment]
@ccashwell: Great, glad it wouldn't just be useful for me. I have some work in progress, I'll ping this thread when I get it tidied up (and tested) and pushed out!

**Comment by zapnap** [comment]
Aha! Having the same issue here. Was wondering why my static error pages (requiring compile-time digest asset references) weren't getting compiled. Very non-obvious, as I assumed the behavior would be limited to the named templates directory without further configuration.

**Comment by chuckd** [comment]
G'day. The related fix, #61, has just been released in 0.1.4 and cleanly breaks our app: we have our assets under frontend/. That's supported by Rails by adding to config.assets.paths in application.rb, so hardcoding app/assets doesn't seem legitimate.

I don't fully understand the various problems that it solved though: it seems one intention is not to compile assets under vendor/assets, but that's no in config.assets.paths on my local app, so perhaps checking against all the paths in config.assets.paths might be legitimate? I'll create a separate PR having a go at that.

**Comment by pitr** [comment]
How about fix #90?
