### ISSUE TITLE
Do we need to check `if app.config.assets`

### ISSUE THREAD

**Issue by whitehat101** [pitr/angular-rails-templates#59]
In the dummy test-app, I commented out the `require "sprockets/railtie"` assuming that that is what created `app.config.assets`, but to my suprise `app.config.assets` was still a truthy value without the sprockets railtie.

In our engine we check `if app.config.assets` before activating our code. But it seems like that check will always return true.

With the sprockets railtie commented, the `if app.config.assets` succeeded, but there was an exception on `app.assets.register_engine`.

Should we come up with a different "do they have sprockets" check, or is it reasonable to assume that if they are trying to use this gem that they are already using sprockets and we can omit the check altogether?

**Comment by pitr** [comment]
Changed to use `defined?(Sprockets::Railtie)`
