### ISSUE TITLE
Templates are not included in JS when precompiling

### ISSUE THREAD

**Issue by elyngved** [pitr/angular-rails-templates#60]
I've been banging my head on this for a couple of days so I figured I'd ask here. In a Rails 3.2.16 app, in app.js I'm using `//= require angular-rails-templates` and then `//= require_tree ./templates` underneath. My templates directory is full of plain .html files and everything is fine and dandy when compiling on the fly in development.

However when I try to precompile assets in any environment, it seems as though the templates files are ignored. The `angular.module("templates",[])` line shows up fine in the compiled, minified app.js file, but nothing after that. It just skips to the next `require`d JS file in the list.

Could it be a certain environment setting that's causing this? Do you know of anything that could cause this? There are no error messages when precompiling, just no templates. I can provide environment info if requested. Thanks

**Comment by anhkind** [comment]
Any updates on how to solve this issue?

**Comment by pitr** [comment]
closing old issue
