### ISSUE TITLE
Common Asset Path with or without Angular Rails Templates?

### ISSUE THREAD

**Issue by kimardenmiller** [pitr/angular-rails-templates#68]
Our Rails templates have always lived in:
```
app/assets/templates
```
So in Angular, it's:
```
.when '/landing',
     templateUrl: '/assets/pages/landing.html'
```
But of course Angular Rails Templates is awesome :boom: , so you install it and change your router to:
```
.when '/landing',
     templateUrl: 'pages/landing.html'
```

But why not code Angular Rails Templates to use the same path? That way if you:
 - Disabled Angular Rails Templates to do some testing, or
 - Angular Rails Templates fails for some other reason

Your templates would still work. Seems $templateCache was actually coded with that in mind.

Is that a good idea, or am I missing some simple Rails setting to easlily make it so?

**Comment by tekt8tket** [comment]
+1

**Comment by pitr** [comment]
The reason for this is so that you know Angular Rails Templates is working correctly before you deploy to production. Since in production you likely have "config.assets.compile = false`, requests to `/assets/pages/landing.html` will fail, but will work fine in development.
