### ISSUE TITLE
angular-rails-templates 0.1.3 breaks on angular-js 1.3.1

### ISSUE THREAD

**Issue by RedRoosterMobile** [pitr/angular-rails-templates#74]
I just discovered that my tooltips do not show up anymore.
I recently upgraded to angular.js 1.3.1. 
There was no js-error or anything like it. I went back to ng 1.3.0 and tooltips where working as expected again.

    <button ng-click='saveSettings()' tooltip-animation="false" tooltip-html-unsafe="{{data.save_tooltip}}" class="btn btn-primary">Save Settings</button>

**Comment by bramski** [comment]
Hmmm.  How did this break?  I'm getting 404 errors trying to use this with angular 1.3.11 and wondering if this is the culprit.

**Comment by pitr** [comment]
closing old task
