### ISSUE TITLE
GET http://localhost:3000/ng/<feature>/templates/<template>.html 404 (Not Found) 

### ISSUE THREAD

**Issue by user453584** [pitr/angular-rails-templates#75]
I'm using [AngularUI Router](https://github.com/angular-ui/ui-router) with this gem, and things were working in development mode using the following route format:

    templateUrl: "ng/<feature>/templates/<template>.html"

with the template files themselves living at: `app/javascripts/ng/<feature>/templates/<template>.html(.erb)`.

However, when I run the app in any mode that concatenates my files (e.g. by deploying to a QA environment or setting `config.assets.debug` to `false`) I get the following error when attempting to request any of my UI Router routes:

    GET http://localhost:3000/ng/<feature>/templates/<template>.html 404 (Not Found) 

I can see all of my templates getting appended to the bottom of the concatenated JS file, but for some reason I'm still getting this 404 for the templates themselves.

I've looked through the other issues and tried various solutions, but so far none has worked.

Where might I be going wrong?

**Comment by pitr** [comment]
closing old task

**Comment by aruprakshit** [comment]
@user453584 How did you fix it? We have the similar problem when doing `config.assets.debug = true` in development.rb file.
