### ISSUE TITLE
Gem try to process unprocessable file.

### ISSUE THREAD

**Issue by pisaq** [pitr/angular-rails-templates#77]
Hi!

I'm trying to use this gem with web components - Google Polymer.
Have installed gem emcee and components via bower, but not rails-bower gem, just bower from console.

So I have an app/assets/components/ folder, where are my own created polymer components in folders and a manifest file - application.html which is including this components like:

```
/<!--
 *= require polymer/polymer
 *= require core-icons/core-icons
-->
```

Bower install its extensions at vendor/assets/components/...

Gem emcee includes to application.html the html_import_tag 'application' so it looks like this:

```
= html_import_tag 'application'
= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'
```

and now when I try to run the application it give me an error:

```
Uncaught ReferenceError: angular is not defined 
application.js?body=1:4 (anonymous function)
```

Gem tries to process the manifest file from emcee to its template view.
It would be fantastic if someone know how to prevent this.

I try to figure it out by changing this:
https://github.com/pisaq/angular-rails-templates/commit/4a32f2aeae7b0d5cb80782c0dd2e6f51b26e9d68

but it is not a workaround :(

When I look to resource tab in inspector it tolds me that there is a applicaction.JS.html file so it change the emcee gem manifest to js.

Maybe I cold fix it somehow in config/application.rb ??

Super Thanks for help.

```
// Angular Rails Template
// source: /Users/piq/Sites/soopagit/app/assets/components/application.html
angular.module("templates").run(["$templateCache", function($templateCache) {
  $templateCache.put("application.html", "<!--\n *= require polymer/polymer\n\n *= require core-icons/core-icons\n *= require core-icon-button/core-icon-button\n *= require core-toolbar/core-toolbar\n *= require core-header-panel/core-header-panel\n *= require paper-tabs/paper-tabs\n *= require paper-tabs/paper-tab\n *= require paper-fab/paper-fab\n *= require paper-input/paper-input\n\n *= require header-panel/header-panel\n *= require menu-sidebar/menu-sidebar\n *= require menu-item/menu-item\n *= require action-button/action-button\n *= require session-window/session-window\n-->")
}]);
```

**Comment by ramyathulasingam** [comment]
I have the same problem and I cant get avoid rails-angular-templates gem at this point of development. Is there there any way to fix the issue.

**Comment by pitr** [comment]
unfortunately, there is very little we can do here, that is just how Rails asset pipeline works. Feel free to come up with a fix.
