### ISSUE TITLE
Use with inline_svg

### ISSUE THREAD

**Issue by manoelneto** [pitr/angular-rails-templates#79]
https://github.com/jamesmartin/inline_svg/

I`m trying to use your gem with this one.

This takes a svg and put it inline for me, but when i use this in a template, i got 

undefined method `inline_svg' for #<#<Class:0x007fd9c8e25e60>:0x007fd9d0bc12e8>

do you know what i can do to get both working?

ps: in normal view, it`s working.

**Comment by pitr** [comment]
do you see this error when you run `rake assets:precompile`?

**Comment by pitr** [comment]
also, could you try these two (separate) things:

1. Setting `config.assets.initialize_on_precompile = true`
2. Downgrade this gem to v0.1.2

**Comment by manoelneto** [comment]
First comment: Yes I see it

Second comment: None of these two worked

I using rails 4.1.8 and inline_svg (0.2.0)

currently i`m using angular-rails-templates (0.1.3) but i tried too with 0.1.2, both crashed.

**Comment by pitr** [comment]
Try adding the following to your initializer
```ruby
Rails.application.assets.context_class.class_eval do
  include ApplicationHelper
  include ActionView::Helpers
  include Rails.application.routes.url_helpers
  include InlineSvg::ActionView::Helpers
end
```

**Comment by maxedison** [comment]
@pitr I was having the same issue, and that solved it. Thanks!

**Comment by manoelneto** [comment]
I didn`t try, my project stoped, but i`m closing as @maxedison said it worked. Thanks!

**Comment by JonaMX** [comment]
I was using `angular-rails-templates` v0.2.0 and today I upgrade to the latest version v1.0.2 and now I'm having this issue

**Comment by TylerKujawa** [comment]
@pitr I am using `angular-rails-template` v 1.0.2 with `inline-svg' and I am using the code snippet you provided above to make the inline-svg helper available to the templates but when I run my application in production mode all of the svgs that are included in angular templates are not being found.  

This is only happening within the angular templates when rails is in production mode. Do you have any ideas why this would be happening?

**Comment by leviwilson** [comment]
> Try adding the following to your initializer
> 
> ```ruby
> Rails.application.assets.context_class.class_eval do
>   include ApplicationHelper
>   include ActionView::Helpers
>   include Rails.application.routes.url_helpers
>   include InlineSvg::ActionView::Helpers
> end
> ```

@pitr to expound upon what @TylerKujawa said, when the `assets:precompile` occurs in production mode, any `inline_svg` calls in our angular templates are never found because they're missing the "slug" at the end of the file.

This does _not_ happen for normal assets that are *not* within an angular-template (normal `.slim` files or whatever).

Any thoughts?

**Comment by leviwilson** [comment]
Opened a separate issue to speak directly to the problem when building `assets:precompile` in production mode.
