### ISSUE TITLE
The usage of ng-include

### ISSUE THREAD

**Issue by dyaa** [pitr/angular-rails-templates#80]
Can you please @pitr tell me how can i use this package with ng-include angular directive.

https://docs.angularjs.org/api/ng/directive/ngInclude

**Comment by BenSmartcheckups** [comment]
I would also like to know!

**Comment by pitr** [comment]
This gem injects templates into `$templateCache `, so I believe it should work with `ng-include`, and `ng-messages`, and whatever else uses `$templateCache` (or `$templateRequest`)

**Comment by pitr** [comment]
@dyaa I updated README with info on how to use ng-include (commit 57ebc260)
