### ISSUE TITLE
Expressions containing single-quotes cause lexer errors

### ISSUE THREAD

**Issue by sbleon** [pitr/angular-rails-templates#86]
@pitr thanks for the great idea! I really want to be able to use this gem, but I've got this odd issue. In my templates (which work fine when I load them on demand), any interpolated expression containing a single-quote results in a lexer error. Replacing single-quotes with double-quotes resolves this issue, but not being able to use single-quotes in JS expressions is unexpected behavior than I don't want to impose on my team.

E.g. `<nav ng-if="isAllowed('viewer')">` results in:
```
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 10-10 [\] in expression [isAllowed(\'viewer\')].
http://errors.angularjs.org/1.3.13/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%2010-10%20%5B%5C%5D&p2=isAllowed(%5C'viewer%5C')
    at REGEX_STRING_REGEXP (http://localhost:3000/assets/angular/angular.js?body=1:64:12)
    at Lexer.throwError (http://localhost:3000/assets/angular/angular.js?body=1:11840:11)
    at Lexer.lex (http://localhost:3000/assets/angular/angular.js?body=1:11799:16)
    at Parser.parse (http://localhost:3000/assets/angular/angular.js?body=1:11960:30)
    at $parse (http://localhost:3000/assets/angular/angular.js?body=1:12679:39)
    at Scope.$get.Scope.$watch (http://localhost:3000/assets/angular/angular.js?body=1:13833:19)
    at ngIfDirective.link (http://localhost:3000/assets/angular/angular.js?body=1:21945:16)
    at invokeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:8220:9)
    at nodeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:7730:11)
    at compositeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:7079:13)
```

**Comment by whitehat101** [comment]
Hi.

Are you using htmlcompressor?

Can you share a (more) complete template that exhibits the issue?

At first, I was suspecting compressor might be normalizing your attribute quotes and not adjusting the values' quotes (I don't recall if it attempts to do this), but I'm also wondering if you're hitting a corner case of our [JS escape class](https://github.com/pitr/angular-rails-templates/blob/master/lib/angular-rails-templates/compact_javascript_escape.rb) that is not being correctly handled.

**Comment by sbleon** [comment]
Thanks, Jeremy. I'm not using htmlcompressor. This problem seems to arise when there are more double-quotes than single-quotes. Here's a full example of what works and what doesn't work:

## Problematic Template
```
<header id="foo"><img ng-src="{{ imagePath('x.png') }}"></header>
```

JS generated:
```
angular.module("templates").run(["$templateCache", function($templateCache) {
  $templateCache.put("_header.html", '<header id="foo"><img ng-src="{{ imagePath(\'x.png\') }}"></header>')
}]);
```

Result:
`Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 10-10 [\] in expression [imagePath(\'x.png\')].`


## OK Template
```
<header><img ng-src="{{ imagePath('x.png') }}"></header>
```

JS generated:
```
angular.module("templates").run(["$templateCache", function($templateCache) {
  $templateCache.put("_header.html", "<header><img ng-src=\"{{ imagePath('x.png') }}\"></header>")
}]);
```

Result: No error.

**Comment by whitehat101** [comment]
Thanks! This will be very helpful.

I think I see what is happening here, but I must be missing something.

I threw both compiled strings (w/o ` id="foo"`) into the console, and at least Chrome believes they are equivalent, and a correct representation of the input template:
```javascript
'<header><img ng-src="{{ imagePath(\'x.png\') }}"></header>' === "<header><img ng-src=\"{{ imagePath('x.png') }}\"></header>" => true
```
```html
<header id="foo"><img ng-src="{{ imagePath('x.png') }}"></header>
```

I wonder if `$templateCache.put` is mangling the strings. I see you're using Angular 1.3.13. (We're currently testing against v1.2.16, something subtle may have changed)

Any chance you're using a 3rd party cache module?

**Comment by sbleon** [comment]
Thanks for looking into this, @whitehat101. I'm not using a 3rd-party cache
module.

I don't think I'm going to use this gem since I've figured out other ways
to improve my template loading. Good luck fixing this issue if you choose
to hunt it down!

**Comment by ruemic** [comment]
+1

**Comment by lehresman** [comment]
I had this same problem and dug in a bit.

This basically comes down to the angular $templateCache not finding the cached version of the template, and making an HTTP request to Rails for the template.  Since we're using the angular-rails-templates gem, when you make a direct request for the template (i.e. GET /templates/mytemplate.html), it delivers the compiled version.  Then Angular tries to parse it as a template, but it's invalid because it's actually JavaScript, not HTML.

The crux of my problem was that I was referencing my templates with the wrong URL.  I was using the url I'd have used to get the template directly from rails.  But this is not how angular-rails-templates caches them.

Pay close attention to the path you're using with templateUrl.  I suspect it's invalid like mine was.

**Comment by sbleon** [comment]
Thanks for the tip, @lehresman. Can you give an example of the wrong URL
you were using with `templateUrl()` and how you fixed it?
