### ISSUE TITLE
Templates are not loading correctly

### ISSUE THREAD

**Issue by tommy7xo** [pitr/angular-rails-templates#87]
Each of my templates loads with stuff like this in the top:
```javascript
// Angular Rails Template
// source: app/assets/templates/template_name.html.haml
angular.module("templates").run(["$templateCache", function($templateCache) {
$templateCache.put("template_name.html", "
```
I dont know where this come from, but probably from this gem. I got
```javascript
//= require angular-rails-templates
//= require_tree ../templates
```
In my application.js

Where this come from, and how to hide this text?

**Comment by simonwalsh** [comment]
Same here.

**Comment by pitr** [comment]
Those comments are coming from here https://github.com/pitr/angular-rails-templates/blob/master/lib/angular-rails-templates/javascript_template.js.erb

Javascript minimization (during production asset pre-compilation) removes JS comments
