### ISSUE TITLE
Is it possible to overwrite @asset_inside_rails_root in the template.rb?

### ISSUE THREAD

**Issue by ramyathulasingam** [pitr/angular-rails-templates#88]
can this be changed  `@asset_inside_rails_root = file.match "#{Rails.root.join 'app', 'assets'} ` to
 `@asset_inside_rails_root = file.match "#{Rails.root.join 'app', 'assets', 'javascripts'}` in my rails application?

I am using the web components and including all the component layouts via html manifest file  (assets/components/application.html), however application.html gets pulled by rails-assets-templates gem at the compilation  and throws an exception. 
Error:
`angular.module("templates").run(["$templateCache", function($templateCache) {
  $templateCache.put("application.html", "// This is a manifest file that'll be compiled into application.html, which will include all the files\n// listed below.\n//\n// Any web component HTML file within this directory or vendor/assets/components, if any,\n// can be referenced here using a relative path.\n//\n\n\n")
}]);`

partial structure of my app's assets folder
* components
  * application.html
* javacripts
  * controllers
  * directives
  * templates

Any thoughts on this? I really appreciate your help.

**Comment by pitr** [comment]
Would #90 work for you?

**Comment by pitr** [comment]
Please try v0.2.0
