### ISSUE TITLE
Using angular-rails-templates in Rails engines

### ISSUE THREAD

**Issue by GarPit** [pitr/angular-rails-templates#91]
0.1.4 version breaks using this gem in rails engine with this line (+ evaluate method):

    @asset_inside_rails_root = file.match "#{Rails.root.join 'app', 'assets', 'javascripts'}

`evaluate` just returns `data` (plain html)

**Comment by lynndylanhurley** [comment]
I'm also unable to use this gem inside of an Engine. Using version 0.1.4 as well.

**Comment by pitr** [comment]
Do you have a suggestion how to fix this? Unfortunately, I don't use this gem in an engine and have no chance to look into this.

**Comment by pitr** [comment]
fixed in v0.2.0 with `inside_paths` config

**Comment by GarPit** [comment]
Good Job! Thanks!

**Comment by Biggless** [comment]
How can I use inside_paths inside rails engine?

I'm getting

```
Showing /Users/name/Documents/app/engines/admin_front/app/views/admin_front/application/home.html where line #6 raised:

couldn't find file 'angular-rails-templates'
```

**Comment by pitr** [comment]
@Biggless Please open a new issue if this is still an issue for you
