### ISSUE TITLE
Templates outside of javascripts directory fails

### ISSUE THREAD

**Issue by mikelorant** [pitr/angular-rails-templates#92]
Based on the documentation example within usage step 2 it should be allowed to use the `app/assets/templates directory`.

```
// Templates in app/assets/templates (but see step 5)
//= require_tree ../templates
```

This causes an `Sprockets::FileOutsidePaths` exception.

Debugging the following in `rails console`
```
Rails.application.config.assets.paths
```

This shows that the `app/assets/templates` directory is not in the asset pipeline paths.

The temporary fix has been the add the following to `config/application.rb`
```
config.assets.paths << Rails.root.join('app/assets/templates')
```

Clarification is required if this is the correct method to use this directory or if this is a bug.

**Comment by pitr** [comment]
That's odd. `app/assets/templates` gets added to asset paths automatically for me. Perhaps it's an old version of rails/sprockets? Either way, your fix is perfectly fine.
