### ISSUE TITLE
Rendering partials in angular templates

### ISSUE THREAD

**Issue by derrickmar** [pitr/angular-rails-templates#94]
I have an Angular template that is used with AngularUI Router

```
            .state('session.view', {
                url: "/:sessionId",
                templateUrl: "view_session/_view_session.html",
                controller: 'ViewSessionController',
            })
```

In ```_view_session.html```, I'm trying to use the rails helper ```render``` to render a partial which is more html for the Angular template.

```<%= render partial: "add_remove_students_modal" %>```

However, I am receiving an error:
```
NameError - undefined local variable or method `view_renderer' for #<#<Class:0x007feffb57b9d8>:0x007ff0019114e8>
```

Other rails helpers like ```link_to``` currently work because I included the ActionView helpers in an initializer like so:

```
Rails.application.assets.context_class.class_eval do
  include ActionView::Helpers
  include Rails.application.routes.url_helpers
end
```

 However, I'm not sure why render is not available.

**Comment by derrickmar** [comment]
P.S. I know there's an angular way of rendering partials with ng-include, but I though there would be more of a rails way since I'm using angular-rails-templates.

**Comment by sashafklein** [comment]
+1

I'm having trouble rendering Rails partials with `ng-include` anyway.

**Comment by erwingaitano** [comment]
+1

I will be awesome to be able to have the 'render' Rails helper. I personally would like to use it for creating templates to generate complex/tedious html structures and just ng-include can't do the job.

**Comment by pitr** [comment]
Yes, unfortunately I was unable to get `render` working as well. Here's my incomplete attempt:
```ruby
# DOES NOT WORK
Rails.application.assets.context_class.class_eval do
  def view_renderer
    ActionView::Base.new.view_renderer
  end
  include ActionView::Helpers
  include Rails.application.routes.url_helpers
end
```

Angular templates are processed during Rails asset compilation. You have no views, controllers, etc. Some of those view helper functions work (like `link_to`) simply because they don't depend on anything. For rendering you need proper view renderer that knows where to look for partials. I think it should be possible to create a proper view renderer though.
